# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# STATIC FILES
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

# SERVER HTTPS
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore/peopleflow.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=peopleflow

# GPS validation radius (km)
gps.validation.radius.km=5

# MAIL CONFIGURATION
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

app.jwt.secret=${JWT_SECRET}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# FILE UPLOAD
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
