spring.application.name=hrapp

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/peopleflow}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:sudheer123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# =========================
# STATIC FILES
# =========================
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/


# =========================
# SERVER HTTPS
# =========================
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore/peopleflow.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=peopleflow


# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkeymysecretkey}
app.jwt.expiration=36000000


# =========================
# GPS VALIDATION
# =========================
gps.validation.radius.km=5


# =========================
# MAIL CONFIGURATION
# =========================
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:connect@renwion.in}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Admin/CEO email
app.admin.email=asha.renwion@gmail.com


# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


spring.profiles.active=dev