package com.hr.hrapp.service;

import com.hr.hrapp.entity.Salary;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import jakarta.servlet.http.HttpServletResponse;

public class PdfGenerator {

    public static void generate(HttpServletResponse response, Salary salary) throws Exception {

        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        // 🔹 Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Paragraph title = new Paragraph("EMPLOYEE PAYSLIP", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(new Paragraph(" ")); // space

        // 🔹 Table
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);

        // Helper method
        addRow(table, "Month", salary.getMonth());
        addRow(table, "Basic Salary", String.valueOf(salary.getBasicSalary()));
        addRow(table, "Net Salary", String.valueOf(salary.getNetSalary()));
        addRow(table, "Hike Amount", String.valueOf(salary.getHikeAmount()));

        document.add(table);

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated by HR System"));

        document.close();
    }

    private static void addRow(PdfPTable table, String key, String value) {
        table.addCell(new PdfPCell(new Phrase(key)));
        table.addCell(new PdfPCell(new Phrase(value)));
    }
}